# Generated by Django 5.1.4 on 2025-01-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='email',
        ),
    ]
