# Generated by Django 5.1.4 on 2025-01-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0002_remove_membre_creation_date_remove_membre_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-13'),
            preserve_default=False,
        ),
    ]
