# Generated by Django 5.1.4 on 2025-01-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0003_membre_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
