# Generated by Django 5.1.4 on 2025-01-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0004_membre_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=250)),
                ('disponibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_bibliothecaire.media')),
                ('dateEmprunt', models.DateTimeField(auto_now_add=True)),
                ('emprunteur', models.CharField(max_length=250)),
            ],
            bases=('app_bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_bibliothecaire.media')),
                ('dateEmprunt', models.DateTimeField(auto_now_add=True)),
                ('emprunteur', models.CharField(max_length=250)),
            ],
            bases=('app_bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_bibliothecaire.media')),
                ('dateEmprunt', models.DateTimeField(auto_now_add=True)),
                ('emprunteur', models.CharField(max_length=250)),
            ],
            bases=('app_bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='PlateauDeJeu',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_bibliothecaire.media')),
                ('nombre_joueurs_min', models.IntegerField()),
            ],
            bases=('app_bibliothecaire.media',),
        ),
    ]
