# Generated by Django 5.1.4 on 2025-01-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0005_media_cd_dvd_livre_plateaudejeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='disponibility',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='plateaudejeu',
            name='nombre_joueurs_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
