# Generated by Django 5.1.4 on 2025-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0006_alter_media_disponibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='cd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteur',
        ),
        migrations.AddField(
            model_name='cd',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dvd',
            name='genre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='nb_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plateaudejeu',
            name='nombre_joueurs_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
