# Generated by Django 5.1.4 on 2025-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0010_rename_plateaudejeu_plateau_alter_media_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='disponibility',
            field=models.BooleanField(default=True),
        ),
    ]
