# Generated by Django 5.1.4 on 2025-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0011_alter_media_disponibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='commentaire_retour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
