# Generated by Django 5.1.4 on 2025-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0012_emprunt_commentaire_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
