# Generated by Django 5.1.4 on 2025-01-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0013_alter_emprunt_date_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='commentaire_retour',
        ),
    ]
