# Generated by Django 5.1.4 on 2025-01-23 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0014_remove_emprunt_commentaire_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
