# Generated by Django 5.1.4 on 2025-01-28 14:49

import app_bibliothecaire.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bibliothecaire', '0015_alter_membre_creation_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plateau',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='Livre',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='nombre_joueurs_max',
            new_name='number_players_max',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='nombre_joueurs_min',
            new_name='number_players_min',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='date_sortie',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='disponibility',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='emprunteur',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='date_emprunt',
            new_name='loan_date',
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('dvd', 'Dvd'), ('cd', 'Cd'), ('board', 'Board')], default='book', max_length=10),
        ),
        migrations.RenameModel(
            old_name='Membre',
            new_name='Member',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(blank=True, null=True)),
                ('expected_return_date', models.DateField(default=app_bibliothecaire.models.get_default_loan_date)),
                ('effective_return_date', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='app_bibliothecaire.member')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='app_bibliothecaire.media')),
            ],
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
